// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6TFM2QOL4SETuZR5M0VPR06IFeyQoo6A',
    appId: '1:74838967499:web:68e816e7b03fd08f78474e',
    messagingSenderId: '74838967499',
    projectId: 'lekh-3caf9',
    authDomain: 'lekh-3caf9.firebaseapp.com',
    storageBucket: 'lekh-3caf9.appspot.com',
    measurementId: 'G-BV4M0ZW4XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzc-0G6JrMSJ2yqpoPFIDK3UbVPqKWPfo',
    appId: '1:74838967499:android:e0b322493b565fbe78474e',
    messagingSenderId: '74838967499',
    projectId: 'lekh-3caf9',
    storageBucket: 'lekh-3caf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdx7Em5bKcUSTRc6cRwBl3mwxfPUumqwM',
    appId: '1:74838967499:ios:fae890c6be2aa73e78474e',
    messagingSenderId: '74838967499',
    projectId: 'lekh-3caf9',
    storageBucket: 'lekh-3caf9.appspot.com',
    iosBundleId: 'cloud.suryansh.lekh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdx7Em5bKcUSTRc6cRwBl3mwxfPUumqwM',
    appId: '1:74838967499:ios:fae890c6be2aa73e78474e',
    messagingSenderId: '74838967499',
    projectId: 'lekh-3caf9',
    storageBucket: 'lekh-3caf9.appspot.com',
    iosBundleId: 'cloud.suryansh.lekh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6TFM2QOL4SETuZR5M0VPR06IFeyQoo6A',
    appId: '1:74838967499:web:93930a9db1f57b7778474e',
    messagingSenderId: '74838967499',
    projectId: 'lekh-3caf9',
    authDomain: 'lekh-3caf9.firebaseapp.com',
    storageBucket: 'lekh-3caf9.appspot.com',
    measurementId: 'G-1YZ86R32WV',
  );
}
